NAME = ft_display_file
FLAGS = -Wall -Wextra -Werror

all: $(NAME)

$(NAME):
	gcc $(FLAGS) ft_display_file.c -o $(NAME)

clean:
	rm -f ft_display_file.o

fclean: clean
	rm ft_display_file

re: fclean $(NAME)
